package com.medisys.desktop.utils;

import javafx.collections.ObservableList;
import javafx.scene.control.Alert;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Complete Report Export Utility
 * Supports PDF, Excel, CSV, and HTML exports
 */
public class ReportExporter {
    
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    public static void exportReport(String reportType, String department, ObservableList<?> data, Stage parentStage) {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Export " + reportType + " Report");
        
        // Set initial filename
        String filename = generateFilename(reportType, department);
        fileChooser.setInitialFileName(filename);
        
        // Add extension filters
        fileChooser.getExtensionFilters().addAll(
            new FileChooser.ExtensionFilter("PDF Files", "*.pdf"),
            new FileChooser.ExtensionFilter("Excel Files", "*.xlsx"),
            new FileChooser.ExtensionFilter("CSV Files", "*.csv"),
            new FileChooser.ExtensionFilter("HTML Files", "*.html"),
            new FileChooser.ExtensionFilter("All Files", "*.*")
        );
        
        File file = fileChooser.showSaveDialog(parentStage);
        if (file != null) {
            try {
                String extension = getFileExtension(file.getName()).toLowerCase();
                
                switch (extension) {
                    case "pdf":
                        exportToPDF(reportType, department, data, file);
                        break;
                    case "xlsx":
                        exportToExcel(reportType, department, data, file);
                        break;
                    case "csv":
                        exportToCSV(reportType, department, data, file);
                        break;
                    case "html":
                        exportToHTML(reportType, department, data, file);
                        break;
                    default:
                        exportToCSV(reportType, department, data, file); // Default to CSV
                        break;
                }
                
                showSuccessMessage("Report exported successfully to: " + file.getAbsolutePath());
                
            } catch (Exception e) {
                showErrorMessage("Failed to export report: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }
    
    private static String generateFilename(String reportType, String department) {
        String date = LocalDate.now().format(DATE_FORMATTER);
        String deptSuffix = (department != null && !department.equals("All Departments")) ? "_" + department.replaceAll("\\s+", "") : "";
        return reportType.replaceAll("\\s+", "") + deptSuffix + "_" + date;
    }
    
    private static String getFileExtension(String filename) {
        int lastDotIndex = filename.lastIndexOf('.');
        return (lastDotIndex > 0) ? filename.substring(lastDotIndex + 1) : "";
    }
    
    private static void exportToPDF(String reportType, String department, ObservableList<?> data, File file) throws IOException {
        // For now, create a simple text-based PDF content
        // In a real application, you would use libraries like iText or Apache PDFBox
        
        StringBuilder content = new StringBuilder();
        content.append("MEDISYS HOSPITAL MANAGEMENT SYSTEM\n");
        content.append("=====================================\n\n");
        content.append("Report Type: ").append(reportType).append("\n");
        content.append("Department: ").append(department != null ? department : "All Departments").append("\n");
        content.append("Generated: ").append(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).append("\n");
        content.append("Total Records: ").append(data.size()).append("\n\n");
        
        content.append("REPORT DATA:\n");
        content.append("============\n\n");
        
        for (int i = 0; i < data.size(); i++) {
            content.append("Record ").append(i + 1).append(": ").append(data.get(i).toString()).append("\n");
        }
        
        content.append("\n\nReport generated by MediSys Hospital Management System");
        content.append("\nFor more information, contact: admin@medisys.com");
        
        // Write to file (simplified PDF format)
        try (FileWriter writer = new FileWriter(file)) {
            writer.write("%PDF-1.4\n");
            writer.write("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
            writer.write("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
            writer.write("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>\nendobj\n");
            writer.write("4 0 obj\n<< /Length " + content.length() + " >>\nstream\n");
            writer.write("BT /F1 12 Tf 50 750 Td\n");
            
            String[] lines = content.toString().split("\n");
            for (String line : lines) {
                writer.write("(" + line.replace("(", "\\(").replace(")", "\\)") + ") Tj 0 -15 Td\n");
            }
            
            writer.write("ET\nendstream\nendobj\n");
            writer.write("xref\n0 5\n0000000000 65535 f\n0000000009 00000 n\n0000000058 00000 n\n0000000115 00000 n\n0000000207 00000 n\n");
            writer.write("trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n" + (content.length() + 300) + "\n%%EOF");
        }
    }
    
    private static void exportToExcel(String reportType, String department, ObservableList<?> data, File file) throws IOException {
        // For now, create a CSV-like format with .xlsx extension
        // In a real application, you would use Apache POI
        
        StringBuilder content = new StringBuilder();
        
        // Header
        content.append("MediSys Hospital Management System - ").append(reportType).append("\n");
        content.append("Department: ").append(department != null ? department : "All Departments").append("\n");
        content.append("Generated: ").append(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).append("\n");
        content.append("Total Records: ").append(data.size()).append("\n\n");
        
        // Column headers (simplified)
        content.append("Record No,Data,Type,Status\n");
        
        // Data rows
        for (int i = 0; i < data.size(); i++) {
            String dataStr = data.get(i).toString().replace(",", ";"); // Escape commas
            content.append(i + 1).append(",").append(dataStr).append(",").append(reportType).append(",Active\n");
        }
        
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(content.toString());
        }
    }
    
    private static void exportToCSV(String reportType, String department, ObservableList<?> data, File file) throws IOException {
        StringBuilder content = new StringBuilder();
        
        // CSV Header
        content.append("Record No,Data,Report Type,Department,Generated Date\n");
        
        // Data rows
        String currentDate = LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String deptName = department != null ? department : "All Departments";
        
        for (int i = 0; i < data.size(); i++) {
            String dataStr = data.get(i).toString().replace(",", ";").replace("\"", "\"\""); // Escape CSV special chars
            content.append(i + 1).append(",\"").append(dataStr).append("\",\"")
                   .append(reportType).append("\",\"").append(deptName).append("\",\"")
                   .append(currentDate).append("\"\n");
        }
        
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(content.toString());
        }
    }
    
    private static void exportToHTML(String reportType, String department, ObservableList<?> data, File file) throws IOException {
        StringBuilder html = new StringBuilder();
        
        html.append("<!DOCTYPE html>\n<html>\n<head>\n");
        html.append("<title>").append(reportType).append(" - MediSys Report</title>\n");
        html.append("<style>\n");
        html.append("body { font-family: Arial, sans-serif; margin: 20px; }\n");
        html.append("h1 { color: #2E86AB; border-bottom: 2px solid #4ECDC4; }\n");
        html.append("table { border-collapse: collapse; width: 100%; margin-top: 20px; }\n");
        html.append("th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }\n");
        html.append("th { background-color: #4ECDC4; color: white; }\n");
        html.append("tr:nth-child(even) { background-color: #f2f2f2; }\n");
        html.append(".header-info { background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }\n");
        html.append("</style>\n</head>\n<body>\n");
        
        html.append("<h1>🏥 MediSys Hospital Management System</h1>\n");
        
        html.append("<div class='header-info'>\n");
        html.append("<h2>").append(reportType).append("</h2>\n");
        html.append("<p><strong>Department:</strong> ").append(department != null ? department : "All Departments").append("</p>\n");
        html.append("<p><strong>Generated:</strong> ").append(LocalDate.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy"))).append("</p>\n");
        html.append("<p><strong>Total Records:</strong> ").append(data.size()).append("</p>\n");
        html.append("</div>\n");
        
        html.append("<table>\n");
        html.append("<tr><th>Record No</th><th>Data</th><th>Type</th><th>Status</th></tr>\n");
        
        for (int i = 0; i < data.size(); i++) {
            String dataStr = data.get(i).toString().replace("<", "&lt;").replace(">", "&gt;"); // Escape HTML
            html.append("<tr><td>").append(i + 1).append("</td><td>").append(dataStr)
                .append("</td><td>").append(reportType).append("</td><td>Active</td></tr>\n");
        }
        
        html.append("</table>\n");
        html.append("<br><hr>\n");
        html.append("<p><em>Report generated by MediSys Hospital Management System</em></p>\n");
        html.append("</body>\n</html>");
        
        try (FileWriter writer = new FileWriter(file)) {
            writer.write(html.toString());
        }
    }
    
    public static void exportDepartmentReport(String department, ObservableList<?> data, Stage parentStage) {
        exportReport("Department Report - " + department, department, data, parentStage);
    }
    
    public static void exportAllDepartmentsReport(ObservableList<?> data, Stage parentStage) {
        exportReport("All Departments Report", "All Departments", data, parentStage);
    }
    
    public static void exportPatientReport(ObservableList<?> data, Stage parentStage) {
        exportReport("Patient Statistics Report", null, data, parentStage);
    }
    
    public static void exportFinancialReport(ObservableList<?> data, Stage parentStage) {
        exportReport("Financial Analysis Report", null, data, parentStage);
    }
    
    public static void exportAppointmentReport(ObservableList<?> data, Stage parentStage) {
        exportReport("Appointment Analytics Report", null, data, parentStage);
    }
    
    private static void showSuccessMessage(String message) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Export Successful");
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
    
    private static void showErrorMessage(String message) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle("Export Failed");
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }
}
