# Configuration file for the Sphinx documentation builder.
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# -- Project information -----------------------------------------------------
project = 'MediSys Hospital Management System'
copyright = f'{datetime.now().year}, Dr. Mazharuddin Mohammed'
author = 'Dr. Mazharuddin Mohammed'
release = '1.0.0'
version = '1.0.0'

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    'sphinx_copybutton',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    '_build', 
    'Thumbs.db', 
    '.DS_Store',
    '**.ipynb_checkpoints',
    'target',
    '*.class',
    '*.jar'
]

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': None,
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_theme_path = []

# Theme options are theme-specific and customize the look and feel of a theme
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'analytics_anonymize_ip': False,
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2563eb',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTMLHelp output ---------------------------------------------
htmlhelp_basename = 'MediSysDoc'

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    'papersize': 'letterpaper',
    'pointsize': '10pt',
    'preamble': '',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'MediSys.tex', 'MediSys Hospital Management System Documentation',
     'Dr. Mazharuddin Mohammed', 'manual'),
]

# -- Options for manual page output ------------------------------------------
man_pages = [
    (master_doc, 'medisys', 'MediSys Hospital Management System Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------
texinfo_documents = [
    (master_doc, 'MediSys', 'MediSys Hospital Management System Documentation',
     author, 'MediSys', 'Enterprise Healthcare Management System.',
     'Miscellaneous'),
]

# -- Options for Epub output -------------------------------------------------
epub_title = project
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# -- Options for todo extension ----------------------------------------------
todo_include_todos = True

# MyST parser removed - using RST only for better compatibility

# -- Custom configuration ----------------------------------------------------

# HTML context for templates
html_context = {
    'display_github': True,
    'github_user': 'Mazharuddin-Mohammed',
    'github_repo': 'MediSysJava',
    'github_version': 'master',
    'conf_py_path': '/docs/',
    'source_suffix': source_suffix,
}

# Logo configuration
html_logo = '_static/images/logo.png'
html_favicon = '_static/images/favicon.ico'

# Custom CSS
html_css_files = [
    'css/custom.css',
]

# Custom JavaScript
html_js_files = [
    'js/custom.js',
]

# Social media and SEO
html_meta = {
    'description': 'Comprehensive documentation for MediSys Hospital Management System - Enterprise healthcare management solution built with Java and JavaFX',
    'keywords': 'hospital management, healthcare software, patient management, medical records, appointment scheduling, Java, JavaFX',
    'author': 'Dr. Mazharuddin Mohammed',
    'viewport': 'width=device-width, initial-scale=1.0',
    'robots': 'index, follow',
    'og:title': 'MediSys Hospital Management System Documentation',
    'og:description': 'Complete documentation for MediSys - Enterprise healthcare management system',
    'og:type': 'website',
    'og:url': 'https://medisysjava.readthedocs.io/',
    'og:image': 'https://medisysjava.readthedocs.io/_static/images/medisys-social-card.png',
    'twitter:card': 'summary_large_image',
    'twitter:title': 'MediSys Hospital Management System',
    'twitter:description': 'Enterprise healthcare management system documentation',
    'twitter:image': 'https://medisysjava.readthedocs.io/_static/images/medisys-social-card.png',
}

# Version warning
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True

# Search configuration
html_search_language = 'en'
html_search_options = {'type': 'default'}

# Copy button configuration for code blocks
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# Navigation configuration
html_use_index = True
html_split_index = False
html_show_sourcelink = True

# Custom footer
html_last_updated_fmt = '%b %d, %Y'
html_use_smartypants = True
html_add_permalinks = '¶'

# External links
extlinks = {
    'github': ('https://github.com/Mazharuddin-Mohammed/MediSysJava/%s', 'GitHub: %s'),
    'issue': ('https://github.com/Mazharuddin-Mohammed/MediSysJava/issues/%s', 'Issue #%s'),
    'pr': ('https://github.com/Mazharuddin-Mohammed/MediSysJava/pull/%s', 'PR #%s'),
}

# Autodoc configuration
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Napoleon extension removed - using basic Sphinx autodoc only
